export const RA_QUESTION_GROUPS = [
  {
    id: 'ra-symptoms',
    title: 'Symptoms & Disease Activity',
    section: 'symptoms',
    questions: [
      {
        id: 'ra-morning-stiffness',
        label: 'Morning stiffness duration (minutes)',
        type: 'numeric',
        min: 0,
        max: 480,
        tooltip: 'Duration >30 minutes is consistent with inflammatory arthritis. Longer stiffness correlates with higher disease activity.',
      },
      {
        id: 'ra-sjc28',
        label: 'Swollen joint count (28-joint assessment)',
        type: 'numeric',
        min: 0,
        max: 28,
        tooltip: '28-joint assessment includes MCP, PIP, wrists, elbows, shoulders, and knees. Core component of DAS28 and CDAI.',
      },
      {
        id: 'ra-tjc28',
        label: 'Tender joint count (28-joint assessment)',
        type: 'numeric',
        min: 0,
        max: 28,
        tooltip: 'Video limitations may affect accuracy of joint tenderness assessment. Consider patient self-report as supplement.',
      },
      {
        id: 'ra-patient-global',
        label: 'Patient global assessment (0–10)',
        type: 'slider',
        min: 0,
        max: 10,
      },
      {
        id: 'ra-provider-global',
        label: 'Provider global assessment (0–10)',
        type: 'slider',
        min: 0,
        max: 10,
        tooltip: 'For video visits, consider being conservative (lower score) given limited physical exam. Document uncertainty.',
      },
      {
        id: 'ra-pain-vas',
        label: 'Pain VAS (0–10)',
        type: 'slider',
        min: 0,
        max: 10,
      },
      {
        id: 'ra-functional-status',
        label: 'Functional status since last visit',
        type: 'radio',
        options: [
          { value: 'improved', label: 'Improved' },
          { value: 'stable', label: 'Stable' },
          { value: 'worsened', label: 'Worsened' },
        ],
      },
      {
        id: 'ra-new-joints',
        label: 'New joint involvement since last visit?',
        type: 'toggle',
        followUp: {
          id: 'ra-new-joints-location',
          label: 'Describe new joint location(s)',
          type: 'text',
        },
      },
      {
        id: 'ra-flares-since-last',
        label: 'Number of flares since last visit',
        type: 'numeric',
        min: 0,
        max: 50,
      },
      {
        id: 'ra-extraarticular',
        label: 'Extra-articular manifestations (select all that apply)',
        type: 'multiselect',
        options: [
          { value: 'nodules', label: 'Rheumatoid nodules' },
          { value: 'ILD', label: 'Interstitial lung disease (ILD)' },
          { value: 'vasculitis', label: 'Vasculitis' },
          { value: 'eye', label: 'Eye involvement (scleritis/episcleritis)' },
        ],
        tooltip: 'RED FLAG: Any new extra-articular manifestation warrants urgent rheumatologist contact. ILD, vasculitis, and scleritis may require immediate escalation.',
      },
      {
        id: 'ra-fatigue',
        label: 'Fatigue (0–10)',
        type: 'slider',
        min: 0,
        max: 10,
      },
      {
        id: 'ra-exercise',
        label: 'Patient engaged in regular exercise?',
        type: 'toggle',
      },
    ],
  },
  {
    id: 'ra-context',
    title: 'Treatment Context & Safety',
    section: 'symptoms',
    questions: [
      {
        id: 'ra-dmard-history',
        label: 'DMARD treatment history',
        type: 'dropdown',
        options: [
          { value: 'naive', label: 'DMARD-naive' },
          { value: 'on-csDMARD', label: 'On csDMARD' },
          { value: 'failed-csDMARD', label: 'Failed csDMARD' },
          { value: 'on-bDMARD', label: 'On bDMARD/tsDMARD' },
          { value: 'failed-bDMARD', label: 'Failed bDMARD/tsDMARD' },
        ],
        tooltip: 'ACR 2021 treatment pathway branches based on DMARD history and disease activity. This drives recommendation logic.',
      },
      {
        id: 'ra-current-biologic-mechanism',
        label: 'Current biologic/targeted therapy mechanism',
        type: 'dropdown',
        options: [
          { value: 'none', label: 'None' },
          { value: 'TNFi', label: 'TNF inhibitor (adalimumab, etanercept, infliximab, etc.)' },
          { value: 'IL-6i', label: 'IL-6 inhibitor (tocilizumab, sarilumab)' },
          { value: 'JAKi', label: 'JAK inhibitor (tofacitinib, baricitinib, upadacitinib)' },
          { value: 'abatacept', label: 'Abatacept (T-cell co-stimulation modulator)' },
          { value: 'rituximab', label: 'Rituximab (B-cell depleting)' },
        ],
        showWhen: (answers) =>
          ['on-bDMARD', 'failed-bDMARD'].includes(answers['ra-dmard-history']),
      },
      {
        id: 'ra-prednisone-duration',
        label: 'Prednisone/glucocorticoid use',
        type: 'dropdown',
        options: [
          { value: 'not on prednisone', label: 'Not on prednisone' },
          { value: '<1 month', label: 'Less than 1 month' },
          { value: '1-3 months', label: '1–3 months' },
          { value: '>3 months', label: 'More than 3 months' },
        ],
        tooltip: 'Long-term glucocorticoid use (>3 months) is a yellow flag. Guidelines recommend bridging only, with structured taper plan.',
      },
      {
        id: 'ra-heart-failure',
        label: 'History of moderate-to-severe heart failure (NYHA III–IV)?',
        type: 'toggle',
        tooltip: 'TNF inhibitors are contraindicated in moderate-to-severe heart failure. This affects biologic selection.',
      },
      {
        id: 'ra-prior-serious-infection',
        label: 'History of prior serious infection?',
        type: 'toggle',
      },
      {
        id: 'ra-hepatitis-b',
        label: 'Hepatitis B (positive HBsAg or anti-HBc)?',
        type: 'toggle',
        tooltip: 'Hepatitis B can reactivate with DMARDs, especially rituximab and TNFi. Antiviral prophylaxis required in many cases.',
      },
      {
        id: 'ra-hepatitis-c',
        label: 'Hepatitis C (active infection)?',
        type: 'toggle',
      },
      {
        id: 'ra-lymphoproliferative-history',
        label: 'History of lymphoproliferative malignancy?',
        type: 'toggle',
        tooltip: 'Prior lymphoma may favor rituximab over TNFi or JAKi for bDMARD selection per ACR 2021 conditional recommendations.',
      },
      {
        id: 'ra-ntb-lung-disease',
        label: 'Non-tuberculous mycobacterial (NTM) lung disease?',
        type: 'toggle',
      },
    ],
  },
];
