export const PSA_QUESTION_GROUPS = [
  {
    id: 'psa-joints',
    title: 'Joint Assessment',
    section: 'symptoms',
    questions: [
      {
        id: 'psa-sjc66',
        label: 'Swollen joint count (66-joint assessment)',
        type: 'numeric',
        min: 0,
        max: 66,
        tooltip: 'The 66-joint count includes small joints of hands and feet excluded from the 28-joint assessment. Used in DAPSA scoring.',
      },
      {
        id: 'psa-tjc68',
        label: 'Tender joint count (68-joint assessment)',
        type: 'numeric',
        min: 0,
        max: 68,
        tooltip: 'The 68-joint count is the standard for PsA and includes all joints from the 66-joint count plus the temporomandibular joints. Used in DAPSA scoring.',
      },
      {
        id: 'psa-patient-pain',
        label: 'Patient pain (0–10)',
        type: 'slider',
        min: 0,
        max: 10,
        tooltip: 'Patient self-reported pain score on 0–10 VAS. Used in DAPSA calculation.',
      },
      {
        id: 'psa-patient-global',
        label: 'Patient global assessment (0–10)',
        type: 'slider',
        min: 0,
        max: 10,
        tooltip: 'Patient global assessment of disease activity on 0–10 VAS. Used in DAPSA calculation.',
      },
      {
        id: 'psa-functional-status',
        label: 'Functional status since last visit',
        type: 'radio',
        options: [
          { value: 'improved', label: 'Improved' },
          { value: 'stable', label: 'Stable' },
          { value: 'worsened', label: 'Worsened' },
        ],
      },
    ],
  },
  {
    id: 'psa-domains',
    title: 'Disease Domains',
    section: 'symptoms',
    questions: [
      {
        id: 'psa-dominant-domain',
        label: 'Dominant disease domain',
        type: 'dropdown',
        options: [
          { value: 'peripheral', label: 'Peripheral arthritis' },
          { value: 'axial', label: 'Axial (spine/sacroiliac joints)' },
          { value: 'enthesitis', label: 'Enthesitis' },
          { value: 'dactylitis', label: 'Dactylitis (sausage digit)' },
          { value: 'skin', label: 'Skin/nail (psoriasis predominant)' },
        ],
        tooltip: 'GRAPPA 2021 uses a domain-based approach to guide treatment selection. Identifying the dominant domain is critical for therapy choice.',
      },
      {
        id: 'psa-axial-symptoms',
        label: 'Axial symptoms present (inflammatory back pain, limited spinal mobility)?',
        type: 'toggle',
        tooltip: 'Inflammatory back pain: onset <40 years, insidious onset, improves with exercise, worse with rest, nocturnal pain. Axial PsA requires different treatment approach (csDMARDs not effective).',
      },
      {
        id: 'psa-enthesitis-sites',
        label: 'Active enthesitis sites (select all that apply)',
        type: 'multiselect',
        options: [
          { value: 'achilles', label: 'Achilles tendon insertion' },
          { value: 'plantar', label: 'Plantar fascia (heel)' },
          { value: 'lateral-epicondyle', label: 'Lateral epicondyle (elbow)' },
          { value: 'patellar', label: 'Patellar tendon (knee)' },
        ],
        tooltip: 'Enthesitis is inflammation at tendon/ligament insertion sites. It is a hallmark of PsA and spondyloarthropathies.',
      },
      {
        id: 'psa-dactylitis',
        label: 'Active dactylitis (sausage digit)?',
        type: 'toggle',
        followUp: {
          id: 'psa-dactylitis-digits',
          label: 'Which digit(s) affected?',
          type: 'text',
        },
      },
    ],
  },
  {
    id: 'psa-skin-nails',
    title: 'Skin & Nail Involvement',
    section: 'symptoms',
    questions: [
      {
        id: 'psa-skin-severity',
        label: 'Psoriasis skin severity',
        type: 'dropdown',
        options: [
          { value: 'none', label: 'No active skin disease' },
          { value: 'mild<3%', label: 'Mild (<3% BSA)' },
          { value: 'moderate3-10%', label: 'Moderate (3–10% BSA)' },
          { value: 'severe>10%', label: 'Severe (>10% BSA or special areas)' },
        ],
        tooltip: 'Skin severity influences biologic choice. IL-17i and IL-23i are preferred when skin disease is significant (BSA >3% or involvement of face, hands, feet, genitals).',
      },
      {
        id: 'psa-new-plaques',
        label: 'New or worsening psoriasis plaques since last visit?',
        type: 'toggle',
      },
      {
        id: 'psa-nail-disease',
        label: 'Nail psoriasis (pitting, onycholysis, subungual hyperkeratosis)?',
        type: 'toggle',
        tooltip: 'Nail psoriasis is associated with more severe PsA, dactylitis, and greater structural damage. IL-17i have demonstrated superior nail efficacy.',
      },
    ],
  },
  {
    id: 'psa-extra',
    title: 'Extra-articular Features & Treatment Context',
    section: 'symptoms',
    questions: [
      {
        id: 'psa-eye-symptoms',
        label: 'Eye symptoms (redness, pain, blurred vision, photophobia)?',
        type: 'toggle',
        tooltip: 'RED FLAG: Eye symptoms may indicate uveitis, which requires urgent ophthalmology evaluation. Uveitis occurs in ~25% of PsA patients. If biologic needed, prefer TNFi monoclonal antibodies over IL-17i.',
      },
      {
        id: 'psa-ibd-history',
        label: 'History of inflammatory bowel disease (Crohn\'s or ulcerative colitis)?',
        type: 'toggle',
        tooltip: 'IL-17 inhibitors can exacerbate or unmask IBD. In patients with IBD history, prefer TNFi monoclonal antibodies (adalimumab, infliximab, certolizumab) or JAK inhibitors.',
      },
      {
        id: 'psa-severity',
        label: 'Overall PsA severity (clinical gestalt)',
        type: 'radio',
        options: [
          { value: 'mild', label: 'Mild — few joints, minimal functional impact' },
          { value: 'moderate', label: 'Moderate — several joints or significant symptoms' },
          { value: 'severe', label: 'Severe — polyarticular, high disease burden, functional impairment' },
        ],
      },
      {
        id: 'psa-treatment-status',
        label: 'Treatment history',
        type: 'dropdown',
        options: [
          { value: 'naive', label: 'Treatment-naive' },
          { value: 'on-csDMARD', label: 'Currently on csDMARD' },
          { value: 'failed-csDMARD', label: 'Failed csDMARD' },
          { value: 'failed-nsaid', label: 'Failed NSAID' },
          { value: 'on-bDMARD', label: 'Currently on biologic/JAKi' },
          { value: 'failed-bDMARD', label: 'Failed biologic/JAKi' },
        ],
        tooltip: 'Treatment history determines the appropriate next step in ACR/GRAPPA recommendations.',
      },
      {
        id: 'psa-flares',
        label: 'Number of PsA flares since last visit',
        type: 'numeric',
        min: 0,
        max: 50,
      },
      {
        id: 'psa-fatigue',
        label: 'Fatigue (0–10)',
        type: 'slider',
        min: 0,
        max: 10,
      },
    ],
  },
  {
    id: 'psa-safety-screening',
    title: 'Safety Screening',
    section: 'symptoms',
    questions: [
      {
        id: 'psa-tb-screening-done',
        label: 'TB screening (PPD or IGRA) completed?',
        type: 'toggle',
        showWhen: (answers) =>
          ['failed-csDMARD', 'failed-bDMARD', 'failed-nsaid'].includes(answers['psa-treatment-status']),
        tooltip: 'TB screening is required before initiating any biologic or JAK inhibitor.',
      },
    ],
  },
  {
    id: 'psa-labs',
    title: 'Laboratory Values',
    section: 'scoring',
    questions: [
      {
        id: 'psa-crp',
        label: 'CRP (mg/L)',
        type: 'numeric',
        min: 0,
        max: 500,
        tooltip: 'C-reactive protein. Used in DAPSA score calculation. Normal <10 mg/L.',
      },
      {
        id: 'psa-esr',
        label: 'ESR (mm/hr)',
        type: 'numeric',
        min: 0,
        max: 150,
        tooltip: 'Erythrocyte sedimentation rate. Useful for monitoring inflammatory burden.',
      },
    ],
  },
];
